name: MacOS/Brew
on: [workflow_dispatch]

jobs:
  macos-brew:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Update Homebrew
        run: |
          brew update
      - name: Install Dependencies
        run: |
          brew install cmake \
                       gettext \
                       pkgconf \
                       adwaita-icon-theme \
                       gspell \
                       gtkmm3 \
                       gtksourceview4 \
                       vte3 \
                       libxml++ \
                       fmt \
                       spdlog \
                       uchardet \
                       fribidi
          brew link icu4c --force
      - name: CI-Build
        run: |
          pkg-config gtkmm-3.0 --cflags --libs
          ls -la /opt/homebrew/Cellar/gtkmm3/3.24.10/lib
          cmake -S . -B build \
                -DCMAKE_FIND_FRAMEWORK=LAST \
                -DBUILD_TESTING='' -DCMAKE_VERBOSE_MAKEFILE=ON
          VERBOSE=1 cmake --build build
          cmake --install build
