name: Windows/MSYS2
on: [workflow_dispatch]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-gtkmm3
            mingw-w64-ucrt-x86_64-gtksourceview4
            mingw-w64-ucrt-x86_64-libxml++2.6
            mingw-w64-ucrt-x86_64-sqlite3
            mingw-w64-ucrt-x86_64-gspell
            mingw-w64-ucrt-x86_64-curl
            mingw-w64-ucrt-x86_64-uchardet
            mingw-w64-ucrt-x86_64-fribidi
            mingw-w64-ucrt-x86_64-fmt
            mingw-w64-ucrt-x86_64-spdlog
            mingw-w64-ucrt-x86_64-texlive-core
            mingw-w64-ucrt-x86_64-gettext
            p7zip
            git
            sed
      - name: CI-Build
        run: |
          scripts/msys2_prepare_standalone.sh
          sed -i 's/C:\\msys64\\home\\PenoneG\\git/D:\\a\\cherrytree/g' scripts/cherrytree.iss
          sed -i 's/C:\\msys64\\home\\PenoneG\\git/D:\\a\\cherrytree/g' scripts/cherrytree_nolatex.iss
      - name: Compile .ISS to .EXE Installer (NOLATEX)
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: scripts/cherrytree_nolatex.iss
          options: /Q
      - name: Compile .ISS to .EXE Installer (FULL)
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: scripts/cherrytree.iss
          options: /Q
      - name: Upload Unsigned Artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/cherrytree*.7z
            build/cherrytree*.exe
          retention-days: 3
          overwrite: true
          if-no-files-found: error
      - name: SignPath Signing
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
          project-slug: 'cherrytree'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: ct-signed
      - name: Upload Signed Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ct-signed
          path: ct-signed
          retention-days: 3
          overwrite: true
          if-no-files-found: error
